version: '3.9'

services:

  backend:
    build:
      context: ../../../Back-ToyotaACE/Back-Toya
      dockerfile: Dockerfile
    container_name: backend_api
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistema_estoque
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: senha_segura_123
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Front_toyota_ace
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # URL usada pelo frontend dentro do docker
      VITE_API_URL: http://localhost:8083/api
      # para Next.js (se existir)
      NEXT_PUBLIC_API_URL: http://localhost:8083/api
    depends_on:
      - backend
  
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_segura_123
      POSTGRES_DB: sistema_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: